Models/Coin.cs
namespace Crypto_Webscrapper.Models
{
    public class Coin
    {
        //properties
        public int  Id { get; set; }
        public string Name { get; set; }
        public string Symbol { get; set; }
        public string imgUrl { get; set; }
        public double CoinValue { get; set; }
        public float Price_Change_24h { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace Crypto_Webscrapper.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Crypto_Webscrapper.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult About()
        {
            return View();
        }
    }
}

Controllers/CryptoController.cs
using Crypto_Webscrapper.Models;
using Crypto_Webscrapper.Objecten;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;




namespace Crypto_Webscrapper.Controllers
{
    public class CryptoController : Controller
    {

        public IActionResult CryptoList()
        {
           
            return View(CryptoObject());   
        }


        public IActionResult CoinValue()
        {
            return View(CryptoObject());
        }
        /// <summary>
        /// returns a crypto object
        /// </summary>
        /// <returns></returns>
        private Crypto CryptoObject()
        {
            Crypto crypto = new Crypto();
            return crypto;
        }

        /// <summary>
        /// returns the result as a json object
        /// </summary>
        /// <param name="id"></param>
        /// <param name="amount"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetResult(string id, string amount)
        {
       
            string json = JsonConvert.SerializeObject(CryptoObject().GetValueOfCoins(id, amount));
            return Json(json);
        }
    }
}

Controllers/HomeController.cs
using Crypto_Webscrapper.Models;
using Crypto_Webscrapper.Objecten;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Crypto_Webscrapper.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;


        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        /// <summary>
        /// Goes to the index page
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

      
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Crypto_Webscrapper.Controllers
{
    public class ProjectsController : Controller
    {
        public IActionResult Projects()
        {
            return View();
        }
    }
}

Views/About/About.cshtml
@{
    ViewData["Title"] = "curriculum vitae";
}
<br />
<br />
<br />
<br />
<div class="container ">
    <main id="main" class="LoadFromBottom">
        <!-- ======= About Section ======= -->
        <section id="about" class="about">
            <div class="container" data-aos="fade-up">
                <div class="section-title">
                    <h2>About Me</h2>
                    <p>
                        Hi, thank you for visiting my website. my name is abdi ali and i am a software engineer.
                        Prior to my current occupation, I completed a one-year internship with Xr group, where I honed my xr and software development skills.
                        In my spare time I like to play a game of fifa or go out with friends
                    </p>
                </div>
                <br />
                <br />
                <div class="row">
                    <div class="col-lg-4">
                        <img src="~/Img/Headshot.png" class="img-fluid">
                    </div>
                    <div class="col-lg-8 pt-4 pt-lg-0 content">
                        <h3>General information</h3>
                        <p class="fst-italic">
                            Driven, loyal and precise are words that describe me well. As a team player,
                            I do not only take into account the interests of the customer, but also those of my colleagues.
                            My affinity with the languages C#, JavaScript, Typescript and PHP enables me to quickly and efficiently realize an idea.
                        </p>
                        <div class="row">
                            <div class="col-lg-6">
                                <ul class="no-bullets">
                                    <li><i class="bi bi-rounded-right"></i> <strong>Birthday:</strong> 1 jan 2001</li>
                                    <li><i class="bi bi-rounded-right"></i> <strong>Website:</strong> <a href="https://abdi-ali.herokuapp.com/">abdi-ali.nl</a></li>
                                    <li><i class="bi bi-rounded-right"></i> <strong>Phone:</strong> +316 492 44907</li>
                                    <li><i class="bi bi-rounded-right"></i> <strong>City:</strong>  Beek lb, Netherlands</li>
                                </ul>
                            </div>
                            <div class="col-lg-6">
                                <ul class="no-bullets">
                                    <li><i class="bi bi-rounded-right"></i> <strong>Age:</strong> 21</li>
                                    <li><i class="bi bi-rounded-right"></i> <strong>Email:</strong> <a href="mailto:ali@ciratum.nl">ali@ciratum.nl</a></li>
                                    <li><i class="bi bi-rounded-right"></i> <strong>Current occupation:</strong> IT Consultant</li>
                                </ul>
                            </div>
                        </div>
                        <br />
                        <p>
                            I also have a great passion for developing video games. Ever since I was young, I liked to write imaginative stories.
                            Through this passion I hope to develop a triple a game
                        </p>
                    </div>
                </div>
            </div>
        </section>
        <!-- End About Section -->
        <!-- ======= Skills Section ======= -->
        <div class="container" data-aos="fade-up">
            <div class="section-title">
                <h2>Skills</h2>
                <p>
                    I tend to view myself as a generalist since I try not to focus on any given technology.
                    My skills range from C#, object oriented programming, asp.net MVC, .NET, typescript, PHP and JavaScript.
                    I have been exposed to a wide variety of technologies in my career and consider myself to be very adaptable.
                </p>
            </div>
            <div class="row skills-content">
                <div class="col-6">
                    <span class="skill">C#</span>
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width: 85%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">85%</div>
                    </div>
                    <span class="skill">Typescript</span>
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width: 80%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">80%</div>
                    </div>
                    <span class="skill">Javascript</span>
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width: 80%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">80%</div>
                    </div>
                </div>
                <div class="col-6">
                    <span class="skill">PHP</span>
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width: 70%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">70%</div>
                    </div>
                    <span class="skill">HTML/CSS</span>
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width: 65%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">65%</div>
                    </div>
                    <span class="skill">Bootstrap 5</span>
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width: 65%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">65%</div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <!-- End #main -->
</div>

Views/Crypto/CoinValue.cshtml
@using Crypto_Webscrapper.Models
@using Crypto_Webscrapper.Controllers;
@model Crypto_Webscrapper.Objecten.Crypto
@{
    ViewData["Title"] = "Calculate Coin Value";
}
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<br />
<br />
<br />
<br />
<div class="container BackgroundTable LoadFromBottom">
    <h2>Coin calculater</h2>
    <label for="CryptoCurrency">Choose the crypto currency</label>
    <select id="cryptoId" class="custom-select" aria-label="Default select example" name="cryptoNameField" required>
        @foreach (KeyValuePair<string, Coin> c in Model.CoinsLibrary)
        {
            <option class="imagebacked" value="@c.Key">@c.Value.Name</option>
        }
    </select>
    <br />
    <label for="cryptoAmount">The amount of your crypto coins</label>
    <input type="number" min="0" class="form-control" name="cryptoAmountField" id="cryptoAmount" placeholder="Enther the amount of crypto you have" required>
    <br />
    <input type="button" id="btnGet" class="btn btn-primary" style="margin-bottom: 5px;" value="how much money do you have" />
</div>
<br />
<br />
<div style="display: none;" class="container  text-center " id="valueContainer">
    <p id="textValueCrypto"></p>
</div>
<script src="~/js/Ajax/Ajax.js"></script>
<script src="~/js/Crypto_Methods/Crypto.js"></script>

Views/Crypto/CryptoList.cshtml
@using Crypto_Webscrapper.Models
@model Crypto_Webscrapper.Objecten.Crypto
@{
    ViewData["Title"] = "Crypto page";
}
<br />
<br />
<br />
<br />
<div class="container">
    <h2>Cypto List</h2>
    <div class="Scroll">
        <table class="table rounded BackgroundTable  LoadFromBottom ">
            <thead>
                <tr class="p">
                    <th scope="col">#</th>
                    <th scope="col">CoinName</th>
                    <th scope="col">Symbol</th>
                    <th scope="col">Value of coin</th>
                    <th scope="col">24h change percentage</th>
                </tr>
            </thead>
            <tbody>
                @foreach (KeyValuePair<string, Coin> c in Model.CoinsLibrary)
                {
                    <tr class="p">
                        <td>@c.Key</td>
                        <td><img src="@c.Value.imgUrl" width="25"> @c.Value.Name</td>
                        <td>@c.Value.Symbol</td>
                        <td>€@c.Value.CoinValue</td>
                        <td class="Price_Change_Container">@c.Value.Price_Change_24h %</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<script src="~/js/Crypto_Methods/Crypto.js"></script>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<section class="background">
    <div class="text-white text-center w-100 hero">
        <h1>I am Abdi Ali</h1>
        <p>And I'm a software engineer</p>
        <a asp-controller="About" asp-action="About" class="btn btn-dark btn-lg">About Me</a>
    </div>

    <footer class="fixed-bottom">
        <div class="container">
            <p>&copy; 2022 Abdi Ali. All rights reserved</p>
        </div>
    </footer>
</section>

Views/Projects/Projects.cshtml
@{
    ViewData["Title"] = "All projects";
}
<br />
<br />
<br />
<br />
<div class="container h-100 LoadFromBottom">
        <div class="text-center">
            <h2>Crypto</h2>
        </div>
        <div class="row h-100 py-2">
            <div class="col-6">
                <div class="card h-100">
                    <div class="card-body">
                        <h3 class="card-title">Crypto list</h3>
                        <p class="card-text">a list with all current crypto coins</p>
                        <a class="btn btn-primary" asp-controller="Crypto" asp-action="CryptoList">See the Crypto List</a>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card h-100">
                    <div class="card-body">
                        <h3 class="card-title">Crypto calculator</h3>
                        <p class="card-text">enter your amount of your crypto coins and see how much it is worth</p>
                        <a class="btn btn-primary" asp-controller="Crypto" asp-action="CoinValue">See the how much your crypto is worth</a>
                    </div>
                </div>
            </div>
        </div>


    <div class="text-center">
        <h2>asp.net mvc and mysqli</h2>
    </div>

    <div class="container h-100">
       <div class="text-center text-white">
        
       </div>
       <div class="row h-100 py-2">
          <div class="col-6">
             <div class="card h-100">
                <div class="card-body">
                   <h3 class="card-title">My own website</h3>
                        <p class="card-text">this website is developed with asp.net mvc </p>
                        <a class="btn btn-primary" href="https://github.com/abdi-ali1/Portfolio">Go to the github link to see the how it is developed</a>
                </div>
             </div>
          </div>
 


          <div class="col-6">
             <div class="card h-100">
                <div class="card-body">
                    <h3 class="card-title">Notes web app</h3>
                    <p class="card-text">a web app where you can log in and create your own notes </p>
                   <button disabled class="btn btn-primary" asp-controller="Crypto" asp-action="CoinValue">Inprogress</button>
                </div>
             </div>
          </div>
       </div>
    </div>

    <div class="text-center">
        <h2>c# oop console.app miniGames</h2>
    </div>

    <div class="container h-100">
        <div class="text-center text-white">
        </div>
        <div class="row h-100 py-2">
            <div class="col-6">
                <div class="card h-100">
                    <div class="card-body">
                        <h3 class="card-title">MiniGames</h3>
                        <p class="card-text">here on this github link you can see how I developed three little mini games</p>
                        <a class="btn btn-primary" href="https://github.com/abdi-ali1/Oefen-Opdrachten">Go to the github link to see the how it is developed</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Portfolio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Crypto_Webscrapper.styles.css" asp-append-version="true" />
  
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark navbar-bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" >
                    Abdi Ali
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <div class="navbar-nav w-100 justify-content-end">
                        <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        <a class="nav-link " asp-area="" asp-controller="About" asp-action="About">About Me</a>
                        <a class="nav-link " asp-area="" asp-controller="Projects" asp-action="Projects">Projects</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
          

            @RenderBody()
        </main>
    </div>
    <br />
    <br />
    
    <footer class=" footertext-muted  text-White" style="padding-bottom: 10px;">
        <div class="container">
            <p>&copy; 2022 Abdi Ali. All rights reserved</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js//Default/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
  